/**
 * @author ColdByDefault
 * @copyright 2026 ColdByDefault
 * @license See License
 * @version canary-v1.1.7
 * @since canary-v1.1.7
 *
 * next-intl type augmentation.
 *
 * Declares the global IntlMessages interface from the generated English
 * messages file so that getMessages(), useTranslations(), and
 * getTranslations() are fully typed instead of returning `any`-indexed
 * AbstractIntlMessages values.
 *
 * The source of truth is messages-src/{locale}/ — messages/en.json is
 * regenerated by `npm run generate:messages`.
 */

import type en from "../messages/en.json";

// Augment use-intl's AppConfig so that Messages resolves to the actual
// shape of messages/en.json instead of the default Record<string, any>.
// This makes getMessages(), useTranslations(), and getTranslations() fully
// typed and silences @typescript-eslint/no-unsafe-assignment on message slots.
declare module "use-intl" {
  interface AppConfig {
    Messages: typeof en;
  }
}
